# author: Herbert Koelman
# created on: 1/6/2019
os: linux

# use Ubuntu Xenial (version 16)
# This comes with cmake 3.11 which is required to build GoogleTest
dist: xenial
language: cpp
compiler: gcc

env:
  CODECOV_TOKEN="73b7985a-7b2d-40fa-a025-65906959f9c2"

# Run travis on these branches only...
branches:
  only:
    - master
    - develop

addons:
  sonarcloud:
    organization: "herbertkoelman-github"

  apt:
    packages:
      - doxygen
      - graphviz

script:
  # Set the variable CMAKE_BUILD_TYPE in your project's settings
  #- mkdir $BUILD_DIRECTORY && cd $BUILD_DIRECTORY && cmake $CMAKE_BUILD_TYPE $CMAKE_COMMAND_LINE_ARGS .. && make $MAKE_TARGETS
  - ./BUILD -S

after_success:
  # create gcov files
  - find ./CMakeFiles/ -type f -name "*.gcno" -exec gcov {} -m \;
  # upload data to codecov
  - bash <(curl -s https://codecov.io/bash)
